# Site settings
title: The mole is digging
author: Alexandr Nikitin
email: nikitin.alexandr.a@gmail.com
description: Things mole encountered while digging his hole
keywords: .NET C#

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://alexandrnikitin.github.io" # the base hostname & protocol for your site

# Google analytics
google_analytics: UA-52186816-3

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: alexandrnikitin
stackoverflow_id: 974487
twitter_username: nikitin_a_a
google_plus_id:
linkedin_username: alexandrnikitin
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
