# Site wide configuration

title: The mole is digging
locale: en_US
url: "https://alexandrnikitin.github.io/blog"

# Jekyll configuration

permalink:   /:title/
markdown:    redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jemoji

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# Site owner
owner:
  name: Alexandr Nikitin
  avatar: bio-photo.jpg
  bio: "Just another bore"
  email: nikitin.alexandr.a@gmail.com
  disqus-shortname: alexandrnikitin
  twitter: nikitin_a_a
  facebook: #username
  google:
    plus: #username
    analytics: UA-52186816-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: alexandrnikitin
  stackoverflow: 974487/alexandr-nikitin
  linkedin: alexandrnikitin
  xing: #username
  instagram: alexandr_a_nikitin
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
